# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuredCCD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('extension', models.CharField(max_length=32)),
                ('expnum', models.IntegerField(default=0)),
                ('exptime', models.FloatField(default=0)),
                ('mjd_obs', models.FloatField(default=0)),
                ('airmass', models.FloatField(default=0)),
                ('racenter', models.FloatField(default=0)),
                ('deccenter', models.FloatField(default=0)),
                ('rabore', models.FloatField(default=0)),
                ('decbore', models.FloatField(default=0)),
                ('band', models.CharField(default=b'', max_length=256)),
                ('ebv', models.FloatField(default=0)),
                ('zeropoint', models.FloatField(default=0)),
                ('transparency', models.FloatField(default=0)),
                ('seeing', models.FloatField(default=0)),
                ('sky', models.FloatField(default=0)),
                ('expfactor', models.FloatField(default=0)),
            ],
        ),
    ]
