# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsdb', '0003_auto_20160203_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredccd',
            name='bad_pixcnt',
            field=models.BooleanField(default=False),
        ),
    ]
