# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsdb', '0004_measuredccd_bad_pixcnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredccd',
            name='readtime',
            field=models.FloatField(default=0),
        ),
    ]
