# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsdb', '0005_measuredccd_readtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredccd',
            name='nmatched',
            field=models.IntegerField(default=-1),
        ),
    ]
