# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsdb', '0007_auto_20160216_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredccd',
            name='obstype',
            field=models.CharField(default=b'object', max_length=64),
        ),
    ]
