# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obsdb', '0008_measuredccd_obstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuredccd',
            name='affine_dx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measuredccd',
            name='affine_dxx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measuredccd',
            name='affine_dxy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measuredccd',
            name='affine_dy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measuredccd',
            name='affine_dyx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measuredccd',
            name='affine_dyy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measuredccd',
            name='affine_x0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='measuredccd',
            name='affine_y0',
            field=models.FloatField(default=0),
        ),
    ]
