# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obsdb', '0009_add_affine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedExptime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.FloatField()),
                ('seqnum', models.IntegerField()),
                ('tileid', models.IntegerField(default=0)),
                ('passnumber', models.IntegerField(default=0)),
                ('band', models.CharField(default=b'', max_length=16)),
                ('airmass', models.FloatField(default=0)),
                ('ebv', models.FloatField(default=0)),
                ('meas_band', models.CharField(default=b'', max_length=16)),
                ('zeropoint', models.FloatField(default=0)),
                ('transparency', models.FloatField(default=0)),
                ('seeing', models.FloatField(default=0)),
                ('sky', models.FloatField(default=0)),
                ('expfactor', models.FloatField(default=0)),
                ('adjfactor', models.FloatField(default=0)),
                ('exptime_unclipped', models.FloatField(default=0)),
                ('exptime_clipped', models.FloatField(default=0)),
                ('exptime_satclipped', models.FloatField(default=0)),
                ('exptime', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtherPasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tileid', models.IntegerField(default=0)),
                ('passnumber', models.IntegerField(default=0)),
                ('depth', models.FloatField(default=0)),
                ('exposure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obsdb.ComputedExptime')),
            ],
        ),
    ]
